### ISSUE TITLE
Some queries

### ISSUE THREAD

**Issue by tanyksg** [Nahoyhp/CS2102_2021_S1_Team35#2]
Do all pet owners need to register with credit card numbers?

How do care takers apply for leave?

**Comment by teoha** [comment]
1. Yes all pet owners are required to register with their credit card numbers
2. Care takers indicate their availability rather than apply for leave. We do not cater for the scenario of emergency leave as mentioned in the project pdf.

**Comment by tanyksg** [comment]
Noted. Thanks.
